name: CI
on: [push, pull_request]
env:
  UI_VERSION: ${{ github.sha }}
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-20.04
    container: httptoolkit/act-build-base
    steps:
      - uses: actions/checkout@v2

      # Install Node 16
      - uses: actions/setup-node@v1
        with:
          node-version: 16.16.0

      - run: npm install -g npm@8.5.5

      # Install & build & test:
      - run: npm ci

      - run: npm run test:unit

      # Build & run normal integration tests:
      - name: Build & test
        run: npm run test:integration
        if: github.ref != 'refs/heads/main'

      # Build with secrets & run integrations tests, on main only:
      - name: Build & test for production release
        run: npm run test:integration
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GA_ID: ${{ secrets.GA_ID }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: http-toolkit
          SENTRY_PROJECT: httptoolkit-ui
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
          if-no-files-found: error
